name: Feature Request
description: Suggest a new idea or enhancement for DUCE.
title: "[Feature]: "
labels: ["Type: Enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature for this project! Please provide details about your proposal below.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of the limitation or frustration you have encountered.
      placeholder: Describe the current limitations.
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of the feature or behavior you want to see implemented.
      placeholder: Describe the proposed solution.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Details of any alternative solutions or workarounds you have considered.
      placeholder: Describe alternatives.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or code examples here.
      placeholder: Add extra details here.
    validations:
      required: false